language: php
sudo: false

php:
- 5.6
- 7.0
- hhvm
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

cache:
   directories:
     - vendor
     - $HOME/.composer/cache

before_script:
- cp app/config/parameters.yml.test app/config/parameters.yml
- composer self-update
- composer install --ignore-platform-reqs --no-interaction --prefer-dist

script:
- phpunit -c app

notifications:
  email:
  - uttnetgroup@gmail.com
  slack:
    secure: DtA5ucKly5MJiE0h8aAi+DmhMzopaHAUa6IU9izyb5KkkfDwFPhS9Ve63w3X3mW5kB9N08Nn9KDCYGUbMr44Nasyq9nfzjQPRya1xH+Skn+hmRId2ezMwX/viZN3m7OQ0qskWjX2Kjn/CTbiIvpBgYjNEDegEDuWRG6ynk+zIfI=
  webhooks:
    urls:
      - https://ungdev.utt.fr/deploy
    on_failure: never
    on_start: never