language: php
sudo: false

php:
- 7.1

env:
    global:
        - SYMFONY_ENV=test
        - SYMFONY_DEBUG=1
        - ETUUTT_DATABASE_DRIVER=pdo_mysql
        - ETUUTT_DATABASE_HOST=db
        - ETUUTT_DATABASE_PORT=
        - ETUUTT_DATABASE_NAME=etuutt
        - ETUUTT_DATABASE_USER=etuutt
        - ETUUTT_DATABASE_PASSWORD=abcdef
        - ETUUTT_APP_ENV=dev
        - ETUUTT_APP_SECRET=27bc50e30a22f453e087ec7d3c88b3f0
        - ETUUTT_MAILER_TRANSPORT=smtp
        - ETUUTT_MAILER_HOST=smtp.utt.fr
        - ETUUTT_MAILER_PORT=25

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_script:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer global require "fxp/composer-asset-plugin:~1.2" --ignore-platform-reqs --no-interaction --prefer-dist || true
    - composer install --ignore-platform-reqs --no-interaction --prefer-dist || true

script:
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no

notifications:
    email:
        - uttnetgroup@gmail.com
    slack:
        secure: DtA5ucKly5MJiE0h8aAi+DmhMzopaHAUa6IU9izyb5KkkfDwFPhS9Ve63w3X3mW5kB9N08Nn9KDCYGUbMr44Nasyq9nfzjQPRya1xH+Skn+hmRId2ezMwX/viZN3m7OQ0qskWjX2Kjn/CTbiIvpBgYjNEDegEDuWRG6ynk+zIfI=
    webhooks:
        urls:
            #- https://ungdev.utt.fr/deploy
            - https://etu.utt.fr/deploy
        on_failure: never
        on_start: never
