language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer update

script: phpunit -c app

notifications:
  email:
    - uttnetgroup@gmail.com
