
parameters:
    logger.exception_listener.class: Etu\Module\LoggerBundle\Logger\ExceptionListener
    logger.request_listener.class: Etu\Module\LoggerBundle\Logger\RequestListener

services:
    logger.exception_listener:
        class: %logger.exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
