
parameters:
    etu.covoit.form.proposal.class: Etu\Module\CovoitBundle\Form\CovoitType
    etu.covoit.form.message.class: Etu\Module\CovoitBundle\Form\CovoitMessageType
    etu.covoit.form.search.class: Etu\Module\CovoitBundle\Form\SearchType

    etu.covoit.query_mapper.search.class: Etu\Module\CovoitBundle\QueryMapper\SearchMapper

    etu.covoit.notifs.new_message.class: Etu\Module\CovoitBundle\Notification\Helper\NewMessageHelper

services:
    etu.covoit.form.proposal:
        class: %etu.covoit.form.proposal.class%

    etu.covoit.form.message:
        class: %etu.covoit.form.message.class%

    etu.covoit.form.search:
        class: %etu.covoit.form.search.class%

    etu.covoit.query_mapper.search:
        class: %etu.covoit.query_mapper.search.class%

    # Notifications helper
    etu.covoit.notifs.new_message:
        class: %etu.covoit.notifs.new_message.class%
        arguments: [@twig]
        tags:
            - { name: etu.notifs_helper }