
parameters:
    etu.covoit.form.proposal.class: Etu\Module\CovoitBundle\Form\CovoitType
    etu.covoit.form.message.class: Etu\Module\CovoitBundle\Form\CovoitMessageType

services:
    etu.covoit.form.proposal:
        class: %etu.covoit.form.proposal.class%

    etu.covoit.form.message:
        class: %etu.covoit.form.message.class%
