imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
#        assets_version: "%version_id%"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true
    assets:
        version: "cachebuster-%version_id%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:            "%kernel.cache_dir%/twig"
    form_themes:
        - 'form/theme-default.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%env(ETUUTT_DATABASE_DRIVER)%"
        host:     "%env(ETUUTT_DATABASE_HOST)%"
        port:     "%env(ETUUTT_DATABASE_PORT)%"
        dbname:   "%env(ETUUTT_DATABASE_NAME)%"
        user:     "%env(ETUUTT_DATABASE_USER)%"
        password: "%env(ETUUTT_DATABASE_PASSWORD)%"
        charset:  UTF8
        server_version: 5.7

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true

                dql:
                    numeric_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        DAY: DoctrineExtensions\Query\Mysql\Day

                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true


# Assetic Configuration
assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles: [ ]
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~


# Minifier Assetic filters names
#minifier:
#    filter:
#        name:
#            css: minifier_css
#            js: minifier_js

# Swiftmailer Configuration
swiftmailer:
    transport: "%env(ETUUTT_MAILER_TRANSPORT)%"
    host:      "%env(ETUUTT_MAILER_HOST)%"
    username:  "%env(ETUUTT_MAILER_USER)%"
    password:  "%env(ETUUTT_MAILER_PASSWORD)%"
    spool:     { type: memory }


# KnpPaginator
knp_paginator:
    page_range: 10                     # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: EtuCoreBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: EtuCoreBundle:Pagination:sortable_link.html.twig # sort link template

# Doctrine extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            # Extensions activated
            tree:           true
            timestampable:  true
            blameable:      false
            sluggable:      false
            translatable:   false
            loggable:       false
            softdeleteable: true
            uploadable:     false

# API Doc
nelmio_api_doc:
    name: EtuUTT API endpoints reference
    sandbox:
        authentication:
            name: access_token
            delivery: query
            custom_endpoint: false

# API Cross-Origin Resource Sharing configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            allow_headers: ['*']
        '^/api/oauth/authorize':
            allow_origin: []
            allow_methods: []
            allow_headers: []

# EtuUTT
etu_core:
    domain: "%env(ETUUTT_DATABASE_PASSWORD)%"
    translation:
        languages: ['en', 'fr', 'de']

etu_user:
    ldap:
        host: "%env(ETUUTT_LDAP_UTT_HOST)%"
        port: 389 #when using env : Invalid type for path "etu_user.ldap.port". Expected int, but got string
    dolibarr:
        host: "%env(ETUUTT_DOLIBARR_HOST)%"
        key: "%env(ETUUTT_DOLIBARR_KEY)%"

    cas:
        version: '2.0'
        host: cas.utt.fr
        port: 443
        path: '/cas/'
        change_session_id: false

etu_module_argentique:
    jwt:
        key: "%argentique_jwt_key%"
        algo: HS256

etu_module_sia:
    ipa:
        user: "%env(ETUUTT_IPA_USER)%"
        password: "%env(ETUUTT_IPA_PASSWORD)%"
        host: "%env(ETUUTT_IPA_HOST)%"
        certificat: "%kernel.root_dir%/../ca.crt"

# Logger
monolog:
    channels: ['admin']
    handlers:
        admin:
            type:     stream
            path:     '%kernel.logs_dir%/admin.log'
            channels: ['admin']

artgris_file_manager:
    web_dir: web
    conf:
        argentique:
            service: 'argentique.filemanagerconfig'

