modules:
    - Etu\Module\AssosBundle\EtuModuleAssosBundle
    - Etu\Module\BugsBundle\EtuModuleBugsBundle
    - Etu\Module\TrombiBundle\EtuModuleTrombiBundle
    - Etu\Module\UVBundle\EtuModuleUVBundle
