modules:
    - Etu\Module\ArgentiqueBundle\EtuModuleArgentiqueBundle
    - Etu\Module\AssosBundle\EtuModuleAssosBundle
    - Etu\Module\BuckUTTBundle\EtuModuleBuckUTTBundle
    - Etu\Module\BugsBundle\EtuModuleBugsBundle
    - Etu\Module\CumulBundle\EtuModuleCumulBundle
    - Etu\Module\CovoitBundle\EtuModuleCovoitBundle
    - Etu\Module\DaymailBundle\EtuModuleDaymailBundle
    - Etu\Module\EventsBundle\EtuModuleEventsBundle
    - Etu\Module\ForumBundle\EtuModuleForumBundle
    - Etu\Module\TrombiBundle\EtuModuleTrombiBundle
    - Etu\Module\UVBundle\EtuModuleUVBundle
    - Etu\Module\UploadBundle\EtuModuleUploadBundle
