parameters:
    database_driver: "%env(ETUUTT_DATABASE_DRIVER)%"
    database_host: "%env(ETUUTT_DATABASE_HOST)%"
    database_port: "%env(ETUUTT_DATABASE_PORT)%"
    database_name: "%env(ETUUTT_DATABASE_NAME)%"
    database_user: "%env(ETUUTT_DATABASE_USER)%"
    database_password: "%env(ETUUTT_DATABASE_PASSWORD)%"
    mailer_transport: "%env(ETUUTT_MAILER_TRANSPORT)%"
    mailer_host: "%env(ETUUTT_MAILER_HOST)%"
    mailer_port: "%env(ETUUTT_MAILER_PORT)%"
    mailer_user: "%env(ETUUTT_MAILER_USER)%"
    mailer_password: "%env(ETUUTT_MAILER_PASSWORD)%"
    secret: "%env(ETUUTT_APP_SECRET)%"
    domain: "%env(ETUUTT_DOMAIN)%"
    dolibarr_host: "%env(ETUUTT_DOLIBARR_HOST)%"
    dolibarr_key: "%env(ETUUTT_DOLIBARR_KEY)%"
    version_id: "%env(ETUUTT_VERSION_ID)%"
    argentique_jwt_key: "%env(ETUUTT_ARGENTIQUE_JWT)%"
    sia_ipa_host: "%env(ETUUTT_IPA_HOST)%"
    sia_ipa_user: "%env(ETUUTT_IPA_USER)%"
    sia_ipa_password: "%env(ETUUTT_IPA_PASSWORD)%"
    slack_webhook_moderation: "%env(ETUUTT_SLACK_WEBHOOK_MODERATION)%"
    slack_token: "%env(ETUUTT_SLACK_TOKEN)%"
    ues_year: "%env(ETUUTT_UES_YEAR)%"
