
# Load the core routes
etu_core:
    resource: "@EtuCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# Load the user routes
etu_user:
    resource: "@EtuUserBundle/Controller/"
    type:     annotation
    prefix:   /

# Load FOS Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Load modules routes
etu_modules:
    resource: .
    type:     modules
    prefix:   /


# Old user search
api_user_search:
    pattern:  /api/users/search/{term}
    options:
        expose: true

# API doc
etu_core_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/reference

etu_core_doc:
    resource: "@EtuCoreApiBundle/Controller/"
    type:     annotation
    prefix:   /api

# Load API from modules
etu_api:
    resource: .
    type:     api
    prefix:   /api