
# Load the core routes
etu_core:
    resource: "@EtuCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# Load the user routes
etu_user:
    resource: "@EtuUserBundle/Controller/"
    type:     annotation
    prefix:   /

# Roundcube index
roundcube_index:
    pattern:  /mail/

# Load FOS Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Load modules routes
etu_modules:
    resource: .
    type:     modules
    prefix:   /
