# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }

    auth.login.listener:
        class: Etu\Core\UserBundle\Security\Firewall\InteractiveLoginListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: security.interactive_login_listener, event: security.interactive_login, method: onLogin }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    ldap:
        class: Symfony\Component\Ldap\Ldap
        arguments: [ '@ext_ldap_adapter' ]
    ext_ldap_adapter:
        class: Symfony\Component\Ldap\Adapter\ExtLdap\Adapter
        arguments:
            - host: "%env(ETUUTT_IPA_HOST)%"
              port: 389
              encryption: none
              options:
                  protocol_version: 3
                  referrals: false
