
parameters:
    etu.notifs.bugs_new_comment.class: Etu\Module\BugsBundle\Notification\Helper\NewCommentHelper
    etu.notifs.bugs_new_opened.class: Etu\Module\BugsBundle\Notification\Helper\NewOpenedHelper

services:

    # Notifications helper
    etu.notifs.bugs_new_comment:
        class: %etu.notifs.bugs_new_comment.class%
        arguments: [@twig]
        tags:
            - { name: etu.notifs_helper }

    etu.notifs.bugs_new_opened:
        class: %etu.notifs.bugs_new_opened.class%
        arguments: [@twig]
        tags:
            - { name: etu.notifs_helper }
