
parameters:
    etu.user.authentication_listener.class: Etu\Core\UserBundle\Security\Listener\KernelListener
    etu.user.crypting.class: Etu\Core\UserBundle\Security\Encrypt\Encrypt
    etu.user.twig.privacy_extension.class: Etu\Core\UserBundle\Twig\Extension\PrivacyExtension
    etu.user.user_type.class: Etu\Core\UserBundle\Form\UserAutocompleteType
    etu.user.ldap.class: Etu\Core\UserBundle\Ldap\LdapManager
    etu.user.sync.class: Etu\Core\UserBundle\Sync\Synchronizer

services:

    # Users authentication
    etu.user.authentication_listener:
        class: %etu.user.authentication_listener.class%
        arguments: [@security.context, @session, @doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # User autocomplete
    etu.user.user_type:
        class: %etu.user.user_type.class%
        tags:
            - { name: form.type, alias: user }

    # LDAP
    etu.user.ldap:
        class: %etu.user.ldap.class%
        arguments: [%etu.ldap.host%, %etu.ldap.port%]

    etu.user.sync:
        class: %etu.user.sync.class%
        arguments: [@etu.user.ldap, @doctrine]

    # Password crypting
    etu.user.crypting:
        class: %etu.user.crypting.class%
        arguments: [%secret%]

    # Privacy
    etu.user.twig.privacy_extension:
        class: %etu.user.twig.privacy_extension.class%
        tags:
            - { name: twig.extension }
