
parameters:
    etu.user.authentication_listener.class: Etu\Core\UserBundle\Security\Listener\KernelListener
    etu.user.crypting.class: Etu\Core\UserBundle\Security\Encrypt\Encrypt
    etu.user.twig.privacy_extension.class: Etu\Core\UserBundle\Twig\Extension\PrivacyExtension
    etu.user.user_type.class: Etu\Core\UserBundle\Form\UserAutocompleteType
    etu.user.ldap.class: Etu\Core\UserBundle\Ldap\LdapManager
    etu.user.sync.class: Etu\Core\UserBundle\Sync\Synchronizer
    etu.user.badges_listener.class: Etu\Core\UserBundle\Model\BadgesManager
    etu.user.cas.authentication.provider.class: Etu\Core\UserBundle\Security\Authentication\Provider\CasProvider
    etu.user.cas.authentication.listener.class: Etu\Core\UserBundle\Security\Firewall\CasListener
    etu.user.every_user.provider.class: Etu\Core\UserBundle\Security\UserProvider\EveryUserProvider

    etu.notifs.new_badge.class: Etu\Core\UserBundle\Notification\Helper\NewBadgeHelper

    etu.api.user.transformer.class: Etu\Core\UserBundle\Api\Transformer\UserTransformer
    etu.api.badge.transformer.class: Etu\Core\UserBundle\Api\Transformer\BadgeTransformer
    etu.api.course.transformer.class: Etu\Core\UserBundle\Api\Transformer\CourseTransformer
    etu.api.user.private_transformer.class: Etu\Core\UserBundle\Api\Transformer\UserPrivateTransformer
    etu.api.orga.transformer.class: Etu\Core\UserBundle\Api\Transformer\OrgaTransformer
    etu.api.orga_member.transformer.class: Etu\Core\UserBundle\Api\Transformer\OrgaMemberTransformer
    etu.api.user_orgas_private.transformer.class: Etu\Core\UserBundle\Api\Transformer\UserOrgasPrivateTransformer

    etu.api.user.mapper.class: Etu\Core\UserBundle\Api\QueryMapper\UserListMapper
    etu.api.orga.mapper.class: Etu\Core\UserBundle\Api\QueryMapper\OrgaListMapper

services:

    # User autocomplete
    etu.user.user_type:
        class: %etu.user.user_type.class%
        tags:
            - { name: form.type, alias: user }

    # LDAP
    etu.user.ldap:
        class: %etu.user.ldap.class%
        arguments: [%etu.ldap.host%, %etu.ldap.port%]

    etu.user.sync:
        class: %etu.user.sync.class%
        arguments: [@etu.user.ldap, @doctrine]

    # Password crypting
    etu.user.crypting:
        class: %etu.user.crypting.class%
        arguments: [%secret%]

    # Authentication
    etu.user.cas.authentication.provider:
        class: %etu.user.cas.authentication.provider.class%
        arguments:
            - '' # User Provider
        public: false

    etu.user.cas.authentication.listener:
        class: %etu.user.cas.authentication.listener.class%
        public: false

    etu.user.every_user.provider:
        class: %etu.user.every_user.provider.class%
        arguments: [@doctrine , @etu.user.ldap]

    # Privacy
    etu.user.twig.privacy_extension:
        class: %etu.user.twig.privacy_extension.class%
        tags:
            - { name: twig.extension }

    # Badges management
    etu.user.badges_listener:
        class: %etu.user.badges_listener.class%
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Notifications helper
    etu.notifs.new_badge:
        class: %etu.notifs.new_badge.class%
        arguments: [@twig]
        tags:
            - { name: etu.notifs_helper }

    # API
    etu.api.badge.transformer:
        class: %etu.api.badge.transformer.class%

    etu.api.course.transformer:
        class: %etu.api.course.transformer.class%

    etu.api.user.transformer:
        class: %etu.api.user.transformer.class%
        arguments: [ @etu.api.badge.transformer ]

    etu.api.user.private_transformer:
        class: %etu.api.user.private_transformer.class%
        arguments: [ @etu.api.badge.transformer ]

    etu.api.orga_member.transformer:
        class: %etu.api.orga_member.transformer.class%
        arguments: [ @etu.api.user.transformer ]

    etu.api.orga.transformer:
        class: %etu.api.orga.transformer.class%
        arguments: [ @etu.api.user.transformer, @etu.api.orga_member.transformer ]

    etu.api.user.mapper:
        class: %etu.api.user.mapper.class%

    etu.api.orga.mapper:
        class: %etu.api.orga.mapper.class%

    etu.api.user_orgas_private.transformer:
        class: %etu.api.user_orgas_private.transformer.class%
        arguments: [ @etu.api.orga.transformer ]
