
parameters:
    etu.user.authentication_listener.class: Etu\Core\UserBundle\Security\Listener\KernelListener
    etu.user.crypting.class: Etu\Core\UserBundle\Security\Encrypt\Encrypt
    etu.user.twig.privacy_extension.class: Etu\Core\UserBundle\Twig\Extension\PrivacyExtension
    etu.user.ldap.class: Etu\Core\UserBundle\Ldap\LdapManager

    etu.notifs.followed_helper.class: Etu\Core\UserBundle\Notification\Helper\FollowedHelper

services:

    # Users authentication
    etu.user.authentication_listener:
        class: %etu.user.authentication_listener.class%
        arguments: [@security.context, @session, @doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # LDAP
    etu.user.ldap:
        class: %etu.user.ldap.class%
        arguments: [%etu.ldap.host%, %etu.ldap.port%]

    # Password crypting
    etu.user.crypting:
        class: %etu.user.crypting.class%
        arguments: [%secret%]

    # Notifications helper
    etu.notifs.followed_helper:
        class: %etu.notifs.followed_helper.class%
        arguments: [@twig]
        tags:
            - { name: etu.notifs_helper }

    # Privacy
    etu.user.twig.privacy_extension:
        class: %etu.user.twig.privacy_extension.class%
        tags:
            - { name: twig.extension }
