
parameters:
    etu.wiki.twig.permissions.class: Etu\Module\WikiBundle\Twig\Extension\PermissionsExtension

services:

    # Twig permissions checker extensio
    etu.wiki.twig.permissions:
        class: %etu.wiki.twig.permissions.class%
        tags:
            - { name: twig.extension }
