
parameters:
    etu.core.modules_manager.class: Etu\Core\CoreBundle\Framework\Module\ModulesManager
    etu.core.routing_loader.class: Etu\Core\CoreBundle\Framework\Routing\ModulesRoutingLoader

    etu.menu.user_builder.class: Etu\Core\CoreBundle\Menu\UserMenu\UserMenuBuilder
    etu.menu.user_renderer.class: Etu\Core\CoreBundle\Menu\UserMenu\UserMenuRenderer
    etu.menu.user_twig_extension.class: Etu\Core\CoreBundle\Twig\Extension\UserMenuRendererExtension

    etu.menu.sidebar_builder.class: Etu\Core\CoreBundle\Menu\Sidebar\SidebarBuilder
    etu.menu.sidebar_renderer.class: Etu\Core\CoreBundle\Menu\Sidebar\SidebarRenderer
    etu.menu.sidebar_twig_extension.class: Etu\Core\CoreBundle\Twig\Extension\SidebarRendererExtension

    etu.modules_boot_listener.class: Etu\Core\CoreBundle\Framework\Listener\ModulesBootListener

    etu.twig.string_manipulation.class: Etu\Core\CoreBundle\Twig\Extension\StringManipulationExtension
    etu.twig.notif_helper.class: Etu\Core\CoreBundle\Twig\Extension\NotificationHelperExtension

    etu.notifs.sender.class: Etu\Core\CoreBundle\Notification\NotificationSender
    etu.notifs.subscriber.class: Etu\Core\CoreBundle\Notification\SubscriptionsManager
    etu.notifs.subscriber.twig.class: Etu\Core\CoreBundle\Twig\Extension\SubscriptionsManagerExtension

    etu.notifs.helper_manager.class: Etu\Core\CoreBundle\Notification\Helper\HelperManager

services:

    # Modules manager
    etu.core.modules_manager:
        class: %etu.core.modules_manager.class%
        arguments: [@kernel]

    # Router register
    etu.core.routing_loader:
        class: %etu.core.routing_loader.class%
        arguments: [@kernel]
        tags:
            - { name: routing.loader }

    # User menu
    etu.menu.user_builder:
        class: %etu.menu.user_builder.class%
        arguments: [@router]
    etu.menu.user_renderer:
        class: %etu.menu.user_renderer.class%
        arguments: [@twig]
    etu.menu.user_twig_extension:
        class: %etu.menu.user_twig_extension.class%
        arguments: [@etu.menu.user_builder, @etu.menu.user_renderer]
        tags:
            - { name: twig.extension }

    # Sidebar
    etu.menu.sidebar_builder:
        class: %etu.menu.sidebar_builder.class%
        arguments: [@router]
    etu.menu.sidebar_renderer:
        class: %etu.menu.sidebar_renderer.class%
        arguments: [@twig]
    etu.menu.sidebar_twig_extension:
        class: %etu.menu.sidebar_twig_extension.class%
        arguments: [@etu.menu.sidebar_builder, @etu.menu.sidebar_renderer]
        tags:
            - { name: twig.extension }

    # Module boot listener
    etu.modules_boot_listener:
        class: %etu.modules_boot_listener.class%
        arguments: [@security.context, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # String manipulation
    etu.twig.string_manipulation:
        class: %etu.twig.string_manipulation.class%
        tags:
            - { name: twig.extension }

    # Notifications helpers
    etu.notifs.helper_manager:
        class: %etu.notifs.helper_manager.class%

    etu.twig.notif_helper:
        class: %etu.twig.notif_helper.class%
        arguments: [@etu.notifs.helper_manager]
        tags:
            - { name: twig.extension }

    # Notifications mangement
    etu.notifs.sender:
        class: %etu.notifs.sender.class%
        arguments: [@doctrine]

    etu.notifs.subscriber:
        class: %etu.notifs.subscriber.class%
        arguments: [@doctrine]

    etu.notifs.subscriber.twig:
        class: %etu.notifs.subscriber.twig.class%
        arguments: [@etu.notifs.subscriber]
        tags:
            - { name: twig.extension }

