
parameters:
    etu.buckutt.soap_builder.class: Etu\Module\BuckUTTBundle\Soap\SoapManagerBuilder
    etu.buckutt.layer.class: Etu\Module\BuckUTTBundle\Layer\BuckUTTLayer

services:
    etu.buckutt.soap_builder:
        class: %etu.buckutt.soap_builder.class%
        arguments: [@session]

    etu.buckutt.layer:
        class: %etu.buckutt.layer.class%
        arguments: [@etu.buckutt.soap_builder]
