
parameters:
    response_format_listener.class: Etu\Core\CoreBundle\Framework\Api\Listener\ResponseFormatListener
    security_proxy.class: Etu\Core\CoreBundle\Framework\Api\Security\AuthenticationProxy

services:
    response_format_listener:
        class: %response_format_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    security_proxy:
        class: %security_proxy.class%
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
